## NumPy Array

my_list = [1,2,3]

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(0,10,2)# it will not include the last number which is 10

array([0, 2, 4, 6, 8])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.ones((4,4,))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.linspace(0,10,8)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

In [11]:
np.linspace(0,10,20)  # last number tells that number of element you want in between the range

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [12]:
np.eye(5)  # it is used to create an identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.random.rand(5)

array([0.15308276, 0.26423686, 0.98367329, 0.39717191, 0.1090625 ])

In [14]:
np.random.rand(5,5)  #rand will give number in between 0-1

array([[0.24141085, 0.70158388, 0.75997892, 0.30517575, 0.81926166],
       [0.02196555, 0.50620964, 0.17093653, 0.65505698, 0.38617554],
       [0.8697818 , 0.90338027, 0.01718237, 0.20917313, 0.27625746],
       [0.05821975, 0.50653989, 0.38587815, 0.78299965, 0.78370639],
       [0.33433306, 0.33669058, 0.25328102, 0.10761018, 0.55940743]])

In [15]:
np.random.randn(5,5)  # randn will give normakl distributed number, gaussian distrubuted number

array([[ 0.37296651, -1.40697842,  1.90012784,  0.69641237,  0.81424467],
       [ 0.34054108, -1.42542885,  0.67490236,  0.03622843, -0.99491873],
       [ 0.77426379,  0.51211991, -0.81493599, -1.91819368,  0.71356207],
       [-1.11426536,  1.1134189 , -0.62321564, -0.99435963, -0.98255785],
       [ 0.09315077,  0.11500487, -2.26666473, -0.03823578, -0.6084062 ]])

In [16]:
np.random.randint(0,100,20)  # random integer in between the give range

array([12, 70, 26, 86, 80, 92, 86, 92, 51, 84, 37, 21, 89, 95, 34, 42, 75,
        1,  4, 88])

In [17]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [18]:
ranarr = np.random.randint(0,50,10)
ranarr

array([39,  6, 25, 25, 31, 35, 22, 49, 30, 18])

In [19]:
mat = arr.reshape(5,5)

In [20]:
np.arange(3)

array([0, 1, 2])

In [21]:
arr.max()

24

In [22]:
arr.argmax()

24

In [23]:
arr.min()

0

In [24]:
arr.argmin()   # arg gives the location of min or max

0

In [25]:
arr.shape

(25,)

In [26]:
mat.shape   # shape will tell you that the shape of the vector or matrix

(5, 5)

In [27]:
from numpy.random import randint

In [28]:
randint(3)

0

### indexing of array

In [29]:
arr = np.arange(0,11)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
arr[5]  #it is used to index the given vector

5

In [32]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [33]:
arr[0:7]

array([0, 1, 2, 3, 4, 5, 6])

In [34]:
arr[3:6]

array([3, 4, 5])

In [35]:
arr[:9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
arr[0:5] = 100
arr    # resetting the arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [38]:
slice_of_arr = arr[:6]
slice_of_arr

array([100, 100, 100, 100, 100,   5])

In [39]:
arr_copy = arr.copy()     # so copy is used to create a copy of a original array and it will not affect previous one

In [40]:
arr_copy

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [41]:
arr_copy[:] = 50

In [42]:
arr_copy

array([50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50])

In [43]:
arr     

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [44]:
mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [45]:
mat[2:,3:]

array([[13, 14],
       [18, 19],
       [23, 24]])

In [46]:
mat[:2,2:]

array([[2, 3, 4],
       [7, 8, 9]])

In [47]:
arr = np.arange(2,12)

In [48]:
arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [50]:
bool_arr = arr > 3
bool_arr

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [52]:
arr[bool_arr]

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [53]:
arr[arr<6]

array([2, 3, 4, 5])

In [62]:
arr = np.random.randint(50,100,50).reshape(5,10)

In [63]:
arr

array([[81, 92, 53, 90, 98, 75, 81, 72, 50, 55],
       [81, 98, 95, 60, 70, 89, 88, 77, 72, 74],
       [77, 83, 52, 85, 76, 70, 81, 99, 75, 58],
       [52, 92, 76, 82, 76, 97, 72, 77, 87, 62],
       [59, 76, 88, 66, 68, 79, 62, 63, 84, 68]])

In [65]:
arr[2,4:6]

array([76, 70])

### NumPy Operations

In [68]:
arr = np.arange(0,10).reshape(2,5)

In [69]:
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [70]:
arr+ arr 

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [71]:
arr * arr

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [72]:
arr/arr

C:\Users\saurabh bhati\AppData\Local\Temp\ipykernel_8176\1862401812.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([[nan,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [73]:
arr + 10

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [74]:
arr/arr

C:\Users\saurabh bhati\AppData\Local\Temp\ipykernel_8176\1862401812.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([[nan,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [75]:
arr = arr+10

In [76]:
arr

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [77]:
arr/arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [79]:
arr**3  # exponent

array([[1000, 1331, 1728, 2197, 2744],
       [3375, 4096, 4913, 5832, 6859]], dtype=int32)

In [80]:
np.sqrt(arr)

array([[3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739],
       [3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894]])

In [81]:
np.exp(arr)

array([[2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06],
       [3.26901737e+06, 8.88611052e+06, 2.41549528e+07, 6.56599691e+07,
        1.78482301e+08]])

In [82]:
np.max(arr)

19

In [83]:
np.sin(arr)

array([[-0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736],
       [ 0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721]])

In [84]:
np.log(arr)

array([[2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733],
       [2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898]])

In [86]:
np.cos(arr)

array([[-0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722],
       [-0.75968791, -0.95765948, -0.27516334,  0.66031671,  0.98870462]])

In [87]:
np.tan(arr)

array([[ 6.48360827e-01, -2.25950846e+02, -6.35859929e-01,
         4.63021133e-01,  7.24460662e+00],
       [-8.55993401e-01,  3.00632242e-01,  3.49391565e+00,
        -1.13731371e+00,  1.51589471e-01]])

In [89]:
np.random.randint(0,1,10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [93]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [96]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [98]:
one = np.ones(10)
one

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [99]:
one*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [101]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [102]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [103]:
np.random.randn(25).reshape(5,5)

array([[-0.12474149,  0.21949271, -0.53218974,  1.20498062,  2.44429034],
       [ 0.69224238,  0.46610396, -0.63325474,  0.05715899,  1.78366688],
       [ 0.21794813, -1.09331279, -1.10538728, -0.43978433, -1.63718003],
       [-0.36360548,  0.55871301, -0.24392515, -0.81848514, -2.85323104],
       [-0.50948516,  0.27540098, -0.7224363 ,  1.17658418, -0.03858132]])

In [114]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [117]:
# or
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [118]:
mat.sum()

300

In [119]:
np.std(mat)

7.211102550927978

In [120]:
mat.std()

7.211102550927978

In [121]:
np.var(mat)

52.0

In [122]:
mat.var()

52.0

In [123]:
np.sin(mat)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849],
       [-0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736],
       [ 0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721],
       [ 0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836]])